### ISSUE TITLE
Travis CI JUnit

### ISSUE THREAD

**Issue by binhonglee** [cst316/spring16project-Go#4]
JUnit seems to work just fine on my own computer successfully but when Travis CI attempts to run it, both tests return errors instead. I think it might have something to do with the memoranda.properties file considering Travis CI does has to create a new one on every build while on a personal computer, it is saved locally in your user folder.

**Comment by aacalde1** [comment]
Close this as I added a commend on travis scrip as i added a `-ant clean` command to clean the build every push.
